//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DolomiteModel.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.Tracks = new HashSet<Track>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Artist { get; set; }
        public Nullable<System.Guid> Art { get; set; }
    
        public virtual ICollection<Track> Tracks { get; set; }
        public virtual Artist Artist1 { get; set; }
    }
}
