//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DolomiteModel.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autoplaylist
    {
        public Autoplaylist()
        {
            this.AutoplaylistRules = new HashSet<AutoplaylistRule>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> Owner { get; set; }
        public string Name { get; set; }
        public Nullable<int> Limit { get; set; }
    
        public virtual ICollection<AutoplaylistRule> AutoplaylistRules { get; set; }
        public virtual User User { get; set; }
    }
}
