//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DolomiteModel.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Autoplaylists = new HashSet<Autoplaylist>();
            this.Playlists = new HashSet<Playlist>();
            this.Tracks = new HashSet<Track>();
            this.Devices = new HashSet<Device>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<Autoplaylist> Autoplaylists { get; set; }
        public virtual ICollection<Playlist> Playlists { get; set; }
        public virtual ICollection<Track> Tracks { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
    }
}
