//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DolomiteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoplaylistRule
    {
        public int Id { get; set; }
        public int Autoplaylist { get; set; }
        public int Rule { get; set; }
        public int MetadataField { get; set; }
        public string Value { get; set; }
    
        public virtual MetadataField MetadataField1 { get; set; }
        public virtual Autoplaylist Autoplaylist1 { get; set; }
        public virtual Rule Rule1 { get; set; }
    }
}
