CREATE TABLE [dbo].[Metadata]
(
	[Id]		BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Track]		BIGINT NOT NULL,
	[Field]		INT NOT NULL,
	[Value]		NVARCHAR(MAX) NOT NULL,
	[WriteOut]	BIT NOT NULL DEFAULT ((0))
)
